DotLiquid/src/DotLiquid.Website/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace DotLiquid.Website.Controllers
{
	[HandleError]
	public class ErrorController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult PageNotFound()
		{
			return View();
		}
	}
}

DotLiquid/src/DotLiquid.Website/Controllers/HomeController.cs
using System.Web.Mvc;

namespace DotLiquid.Website.Controllers
{
	[HandleError]
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

DotLiquid/src/DotLiquid.Website/Controllers/TryOnlineController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DotLiquid.Website.Controllers
{
	[HandleError]
	public class TryOnlineController : Controller
	{
		public ActionResult Index()
		{
			const string templateCode = @"&lt;p&gt;{{ user.name | upcase }} has to do:&lt;/p&gt;

&lt;ul&gt;
{% for item in user.tasks -%}
  &lt;li&gt;{{ item.name }}&lt;/li&gt;
{% endfor -%}
&lt;/ul&gt;";

			string result = LiquifyInternal(templateCode);

			ViewData["TemplateCode"] = templateCode;
			ViewData["Result"] = result;

			return View();
		}

		[HttpPost]
		public ActionResult Liquify(string templateCode)
		{
			string result = LiquifyInternal(templateCode);

			return new ContentResult
			{
				Content = result
			};
		}

		private static string LiquifyInternal(string templateCode)
		{
			Template template = Template.Parse(templateCode);
			return template.Render(Hash.FromAnonymousObject(new
			{
				user = new User
				{
					Name = "Tim Jones",
					Tasks = new List<Task>
					{
						new Task { Name = "Documentation" },
						new Task { Name = "Code comments" }
					}
				}
			}));
		}
	}

	public class User : Drop
	{
		public string Name { get; set; }
		public List<Task> Tasks { get; set; }
	}

	public class Task : Drop
	{
		public string Name { get; set; }
	}
}

DotLiquid/src/DotLiquid.Website/Views/Home/Index.cshtml
<div id="content">
	<h1>What is DotLiquid?</h1>
	<p>DotLiquid is a templating system ported to the .net framework from 
	Ruby’s <a href="http://www.liquidmarkup.org">Liquid Markup</a>.</p><blockquote><p>It’s <strong>easy</strong> to learn, <strong>fast</strong> and <strong>safe</strong></p></blockquote><p>You can have 
	your users build their own templates without affecting your server security in any way.</p>

	<h2>Requirements</h2>
	<p>.NET Framework 3.5 or above</p>

	<h2>License</h2>
	<p>DotLiquid is intended to be used in both open-source and commercial environments. To allow its use in as many
		situations as possible, DotLiquid is dual-licensed. You may choose to use DotLiquid under either the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>
		, or the <a href="http://www.microsoft.com/opensource/licenses.mspx#Ms-PL">Microsoft Public License (Ms-PL)</a>. These licenses are essentially identical, but you are
		encouraged to evaluate both to determine which best fits your intended use.</p>
	
	<h2>Around the web</h2>
	<ul>
		<li><a href="http://blog.mattbrailsford.com/2012/05/13/dotliquid-viewengine-now-available-on-the-nuget-gallery/">DotLiquid ViewEngine Now Available On The NuGet Gallery</a></li>
		<li><a href="http://www.infoq.com/news/2011/12/Liquid-Markup">Safe User-Generated Templates for Ruby and .NET</a></li>
		<li><a href="http://jbaurle.wordpress.com/2011/05/04/how-to-implement-a-generic-template-engine-for-sharepoint-2010-using-dotliquid/">How To Implement A Template Engine For SharePoint Using DotLiquid</a></li>
		<li><a href="http://timjones.tw/blog/archive/2010/10/25/introducing-dotliquid-the-secure-open-source-template-engine">Introducing DotLiquid: the secure, open-source template engine for .NET</a></li>
	</ul>
</div>
<div id="side">
	<h1>What does it look like?</h1>
	<div class="sample-code">
		<p>...</p>
		<p>&lt;p&gt;<span class="code">{{ user.name }}</span> has to do:&lt;/p&gt;</p>
		<p>&lt;ul&gt;</p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;<span class="code">{% for item in user.tasks -%}</span></p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;<span class="code">{{ item.name }}</span>&lt;/li&gt;</p>
		<p>&nbsp;&nbsp;&nbsp;&nbsp;<span class="code">{% endfor -%}</span></p>
		<p>&lt;/ul&gt;</p>
		<p>...</p>
	</div>

	<h2>Get started</h2>
	<p>
		If you use <a href="http://nuget.org">NuGet</a>, then the easiest way to get DotLiquid is to install the <a href="http://nuget.org/List/Packages/DotLiquid">DotLiquid NuGet package</a>.
		<br /><br />

		Otherwise, grab the current version from <a href="http://github.com/formosatek/dotliquid/downloads">here</a>
		or get the latest bits from <a href="http://github.com/formosatek/dotliquid">github</a> and compile it.
		<br/><br/>

		Read our <a href="http://github.com/formosatek/dotliquid/wiki">documentation</a>. Ask questions on the
		<a href="http://groups.google.com/group/dotliquid">DotLiquid Google Group</a> or <a href="http://twitter.com/dotliquid">Twitter</a>.
	</p>
	
	<h2>Projects that use DotLiquid</h2>
	<ul>
		<li><a href="http://nuget.org/packages/DotLiquid.ViewEngine">DotLiquid View Engine for ASP.NET MVC</a></li>
		<li><a href="http://nuget.org/packages/Nancy.Viewengines.DotLiquid">DotLiquid View Engine for Nancy</a></li>
	</ul>
</div>

DotLiquid/src/DotLiquid.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="description" content="DotLiquid is a templating system ported to the .net framework from Ruby’s Liquid Markup" />
	<link href="/assets/css/reset.css" rel="stylesheet" type="text/css" />
	<link href="/assets/css/main.css" rel="stylesheet" type="text/css" />
	<!--[if !IE 7]>
	<style type="text/css">
	#wrap {
		display: table;
		height: 100%;
	}
	</style>
	<![endif]-->
	@RenderSection("StyleContent", false)

	<title>Welcome to DotLiquid, a safe templating system for .net</title>

	@if (!Request.IsLocal) {
	<script type="text/javascript">

		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-5166698-3']);
		_gaq.push(['_trackPageview']);

		(function () {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

	</script>
	}
</head>
<body>
	<div id="wrap">
		<div id="main" class="clearfix">
			<div id="header" class="clearfix">
				<div id="logo">
					<img src="/assets/img/logo_big.png" alt="DotLiquid Logo" title="DotLiquid Home" />
				</div>
				<ul id="header-menu">
					<li><a class="@(Html.IsCurrentAction("index", "home") ? "active" : "")" href="/">home</a></li>
					<li><a href="http://github.com/formosatek/dotliquid/downloads">download</a></li>
					<li><a href="http://github.com/formosatek/dotliquid/wiki/">learn</a></li>
				</ul>
				<div id="try">
					<a href="@Url.Action("Index", "TryOnline")">
						<img src="/assets/img/try_btn.png" alt="Try it online" title="Try it online" /></a>
				</div>
			</div>
			@RenderBody()
		</div>
	</div>
	<div id="footer">
		<div id="footer-content" class="clearfix">
			<div class="footer-col">
				<h5>Porting and Development</h5>
				<ul>
					<li><a href="http://timjones.tw">Tim Jones</a></li>
				</ul>
				<h5>Contributors</h5>
				<ul>
					<li><a href="http://www.alessandropetrelli.com">Alessandro Petrelli</a></li>
				</ul>
			</div>
			<div class="footer-col">
				<h5>Documentation</h5>
				<ul>
					<li><a href="http://github.com/formosatek/dotliquid/wiki/DotLiquid-for-Developers">For Developers</a></li>
					<li><a href="http://github.com/formosatek/dotliquid/wiki/DotLiquid-for-Designers">For Designers</a></li>
				</ul>

				<h5>Support</h5>
				<ul>
					<li><a href="http://groups.google.com/group/dotliquid">Google Group</a></li>
					<li><a href="http://twitter.com/dotliquid">Twitter</a></li>
				</ul>
			</div>
			<div class="footer-col">
				<h5>License</h5>
				<ul>
					<li><a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a></li>
					<li><a href="http://www.microsoft.com/opensource/licenses.mspx#Ms-PL">Microsoft Public License<br />(Ms-PL)</a></li>
				</ul>
			</div>
			<div class="footer-col last">
				<h5>Sponsors</h5>
				<p>Our thanks to <a href="http://www.jetbrains.com">JetBrains</a> for donating licenses for <a href="http://www.jetbrains.com/resharper/">ReSharper</a>,
				<a href="http://www.jetbrains.com/profiler/">dotTrace</a> and <a href="http://www.jetbrains.com/dotcover/">dotCover</a>.</p>
				<p>Thanks also to <a href="http://appharbor.com">AppHarbor</a> for providing free hosting for this website.</p>
			</div>
		</div>
		<div id="copyright">
			Copyright ©2010-2012 <a href="http://formosatek.com">Formosatek</a> and contributors - All rights reserved. 
			Site design by <a href="http://www.alessandropetrelli.com">Alessandro Petrelli</a>.
			Hosted free by <a href="http://appharbor.com">AppHarbor</a>.
		</div>
	</div>
	
	@RenderSection("ScriptContent", false)
</body>
</html>

DotLiquid/src/DotLiquid.Website/Views/TryOnline/Index.cshtml
<div id="content">
	<h1>Try DotLiquid Online</h1>

	<p>This page lets you interactively try out the DotLiquid templating system. It's also proof
		that it's okay to allow your users to edit their own templates - if we trust it so can you!</p>
	<br />

	<h3>Template Code</h3>
	<form action="#">
		<textarea name="templateCode" id="templateCode">@Html.Raw(ViewData["TemplateCode"] as string)</textarea>
	</form>
	<br />

	<h3>Result</h3>
	<pre class="result">@Html.Raw(ViewData["Result"] as string)</pre>
	<br />
</div>
<div id="side">
	<h1>Instructions</h1>
	<p>The available objects are structured and created as follows:</p>
	<br />
	<div class="sample-code smaller-code">
		<p>
			public class User : Drop<br />
			{<br />
			&nbsp;&nbsp;public string Name { get; set; }<br />
			&nbsp;&nbsp;public List&lt;Task&gt; Tasks { get; set; }<br />
			}<br />
			<br />
			public class Task<br />
			{<br />
			&nbsp;&nbsp;public string Name { get; set; }<br />
			}<br />
			<br />
			user = new User<br />
			{<br />
			&nbsp;&nbsp;Name = "Tim Jones",<br />
			&nbsp;&nbsp;Tasks = new List&lt;Task&gt;<br />
			&nbsp;&nbsp;{<br />
			&nbsp;&nbsp;&nbsp;&nbsp;new Task { Name = "Documentation" },<br />
			&nbsp;&nbsp;&nbsp;&nbsp;new Task { Name = "Code comments" }<br />
			&nbsp;&nbsp;}<br />
			}<br />
		</p>
	</div>
	<br />
	<p>You can refer to the <a href="http://github.com/formosatek/dotliquid/wiki/DotLiquid-for-Designers">DotLiquid for Designers</a> wiki page
		to find out which tags and filters are available.</p>
	<h2>How does this work?</h2>
	<p>Why not have a look at the <a href="http://github.com/formosatek/dotliquid/tree/master/src/DotLiquid.Website/Controllers/TryOnlineController.cs">source code</a> of the page you're looking at now?</p>
</div>

@section ScriptContent {
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
	<script type="text/javascript" src="/assets/js/jquery.observe_field.js"></script>

	<script type="text/javascript">
		function liquify(textarea) {
			var templateCode = $('<div/>').text(textarea.value).html();
			$.post('@Url.Action("Liquify")', { templateCode: templateCode }, function (data) {
				$(".result").html(data);
			});
		}

		$(function () {
			//$("#liquify").hide();

			$("#templateCode").observe_field(0.5, function () {
				liquify(this);
			});
		});
	</script>
}